server:
  port: 8080

spring:
  application:
    name: print-backend
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/print_management?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: boss.1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.print.module.*.entity
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: YTJkZm5hM2tkZm5ha3NmZG5ha3NmZGFuc2RmbmFzZGZua2FzZGZrbmFzZGZrbg==
  expiration: 86400000

logging:
  level:
    com.print: debug
